#'@name missinExtents
#'@title write missing extention into catalog.exe generated .csv 
#'
#'@description
#' writes missing extention into catalog.exe generated .csv by substringing .las filename
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param catalogTable  default is \code{NULL} .csv generated by catalog.exe
#'
#'@examples
#'\dontrun{
#' # repair loaded .csv and store in new object
#' oldTable<-read.csv(paste0(filepath, lasfilename,".csv))
#' newTable<-missingExtents(oldTable)
#'}
#'


missingExtents<-function(catalogTable){
  
  for (i in 3:nrow(catalogTable)){
    
    findrows <- which(catalogTable$MinX ==0|catalogTable$MinY==0|
                        catalogTable$MaxX==0|catalogTable$MaxY==0)
    
    for (j in findrows){
      coor<-substr(catalogTable[j,1],nchar(as.character(catalogTable[j,1]))-10, nchar(as.character(catalogTable[j,1])))
      
      xmin<-paste0(substr(coor, 1,3), "000")
      
      ymin<-paste0(substr(coor, 4,7), "000")
      
      catalogTable[j,]$MinX=as.numeric(xmin)
      
      catalogTable[j,]$MinY=as.numeric(ymin)
    }}
  
  
  return(catalogTable)
  
}


#'@name GroundSurfaceCreate
#'@title Create a DEM raster* object and Catalogtables from a LiDAR generated point cloud.
#'
#'@description
#' Create a DEM raster* object from a LiDAR generated point cloud based on regular las format files
#' Output is required for most Fusion Operations
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param res resolution for raster operations 
#'@examples
#'\dontrun{
#' # create a DSM based on a uav point cloud 
#' GroundSurfaceCreate(lasFiles = lasFiles, res=10)
#'}
#'
GroundSurfaceCreate<-function(lasFiles, res ){
  
  
  paramList <- c(paste(as.character(res),"M M 1 32 0 0 "))
  
  
  for (i in 1:length(lasFiles)) {
    ### --> retrieve infomation from las file
    
    
    # calculate extents etc...
    
    #--> Fusion catalog if not allready exists
    
    command<-Fusion
    command<-paste0(command, "catalog.exe")
    command<-paste0(command," ", gi_input, basename(lasFiles[i]) )
    command<-paste0(command," ", gi_run,lasFiles[i],".html"   )
    system(command)
    
    #--> extract extent info 
    info <- read.csv(paste0(gi_run,lasFiles[i],".csv"))
    #fix extent
    
    info2<-missingExtents(info)
    #TODO  fix error in las files if (as.numeric(info[[2]][3])) fixLas()
    #--> define extent for further calculation
    extent<-paste(as.numeric(info2$MinX),as.numeric(info2$MinY),as.numeric(info2$MaxX),as.numeric(info2$MaxY))
    ext<-c(as.numeric(info2$MinX),as.numeric(info2$MinY),as.numeric(info2$MaxX),as.numeric(info2$MaxY))
    
    
    #--> Create a .las with groundpoints only 
    command<-Fusion
    command<-paste0(command, "clipdata.exe")
    command<-paste0(command," ","/class:2 ")
    command<-paste0(command," ", gi_input, basename(lasFiles[i])   )
    command<-paste0(command," ", gi_run,"ground_",basename(lasFiles[i])   )
    command<-paste0(command," ", extent)
    system(command)  
    
    #--> Create the required PLANS DTM format 
    command<-Fusion
    command<-paste0(command, "gridsurfacecreate.exe")
    command<-paste0(command," ", gi_run,"surf_",basename(lasFiles[i]),".dtm")
    command<-paste0(command," ", paramList  )
    command<-paste0(command," ", gi_run,"ground_",basename(lasFiles[i])   )
    system(command)}
  
}



#'@name gridMetrics
#'@title calculate elevation and intensity based metrics an write out selected metrics to raster (.asc)
#'
#'@description
#' calculate elevation and intensity based metrics an write out selected metrics to raster (.asc)
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClasses default is \code{list(c(0,2,5,10,30))} 
#'@param heightbreak lower heightbreak
#'@param res  default is \code{NULL} cellsize
#'@param metrics  default is  \code{list(c(0,2,5,10,30))} list of metric indexes indexes given 
#'in Fusion Manual p.78/79
#'@param buffer optional parameter \code{NULL} if extent should be extendet by a buffer
#'@param cellbuffer optional parameter \code{NULL} if cellbased metrics should
#' take neighbouring cells into account
#'@param strata optional paramter \code{list(c(0,2,5,10,30))}, elevation based metrics
#' will be calculated for strata
#'@param instrata optional paramter \code{list(c(0,2,5,10,30))}, intensity based metrics
#' will be calculated for strata
#'@examples
#'\dontrun{
#' 
#'GridMetrics(lasFiles = lasFiles, res = gridsize, heightClassList = h, metrics = 31, heightbreak=0.2 )
#'
#'
#'
GridMetrics<-function(lasFiles,
                      res, 
                      heightClassList,
                      metrics,
                      heightbreak,
                      buffer,
                      cellbuffer,
                      strata, instrata ){
  metric<-raster::stack()
  m<-list()
  #metr<-vector("list", length(lasFiles))
  for (i in 1:length(lasFiles)){
    
    #  heightClassList to string if strata or instrata is set
    slices<-paste(unlist(heightClassList), collapse = ",")
    
    #calculate gridmetrics
    command<-Fusion
    command<-paste0(command, "gridmetrics.exe ")
    #command<-paste0(command,"/gridxy:", extent )
    
    #set switches- switches will not be defined if argument is missing in function call
    ifelse(!missing(buffer), command<-paste0(command, " /buffer:", 
                                             buffer), command<-command)
    ifelse(!missing(cellbuffer), command<-paste0(" /cellbuffer:", 
                                                 cellbuffer), command<-command)
    ifelse(!missing(strata), command<-paste0(" /strata:", 
                                             slices), command<-command)
    ifelse(!missing(instrata), command<-paste0(" /instrata:", 
                                               slices), command<-command)
    # set basic parameters
    command<-paste0(command," ", gi_run,"surf_",lasFiles[i],".dtm")
    command<-paste0(command, " ", heightbreak)
    command<-paste0(command, " ", res)
    command<-paste0(command," ", gi_run,lasFiles[i], "_GridMetrics.csv"   )
    command<-paste0(command," ", gi_input, lasFiles[i])
    system(command) 
    
    #create ascii raster from gridmetrics, for column indexing look up indexes given 
    #in Fusion Manual p.78/79
    
    
    
    for (j in 1:length(metrics)){
      
      command<-Fusion
      command<-paste0(command, "csv2grid.exe")
      command<-paste0(command, " ",  gi_run,lasFiles[i], "_GridMetrics_all_returns_elevation_stats.csv")
      command<-paste0(command, " ", metrics[j])
      command<-paste0(command, " ", gi_output, lasFiles[i],"_","elevationMetrics",metrics[j], ".asc")
      system(command) 
      
      
      
      
      r <- raster::raster(paste0(gi_output, lasFiles[i],"_","elevationMetrics",metrics[j], ".asc"),quick=T, crs=proj4)
      r[r[]==NAvalue(r)]<-NA  #replace arbitrary NA values with "NA"
      if (j>1) r <- raster::resample(r, rold, method = 'bilinear')
      rold<-r
      metric<-raster::stack(metric,r,quick=T)
      
    } 
    #raster::setExtent(metric,ext)
    #raster::crs(metric)<- proj4
    m[[i]]<-metric
    metric<-raster::stack()
    
  }
  
  return(m)
  
}





#'@name fu_sliceRas
#'@title Create a raster* object from a LiDAR generated point cloud 
#'
#'@description
#' Create a raster* object from a LiDAR generated point cloud based on regular las format files
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param zrange default is \code{list(c(0,3), c(3,15))} list vector pairs describing the vertical slice 
#'@param paramList default is \code{c("1 M M 1 32 0 0 ")}list of parameters for info see clipdata.exe manual 
#'@param res resolution for raster operations 
#'@param proj4  any valid proj4 string that is assumingly the correct one default is \code{"+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"}
#'
#'@examples
#'\dontrun{
#' # create a DSM based on a uav point cloud 
#' r<-lasSlice(lasFiles = lasFiles)
#'}zrange[j],"_",zrange[j+1]
#'


fu_sliceRas<- function(lasFiles = NULL,
                       zrange =  NULL,
                       zrnames = NULL,
                       paramList=c("1 M M 1 32 0 0 "),
                       res= 10,
                       proj4 = "+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
) {
  
  paramList <- c(paste(as.character(gridsize),"M M 1 32 0 0 "))
  density<-raster::stack()
  d<-list()
  
  
  for (i in 1:length(lasFiles)) {

  
      for (j in 1:length(zrange)){
        info <- strsplit(readLines(paste0(gi_output,lasFiles[i],".csv"),encoding = "utf-8"),split = ",")
        
        #TODO  fix error in las files if (as.numeric(info[[2]][3])) fixLas()
        #--> define extent for further calculation
        extent<-paste(as.numeric(info[[2]][3]),as.numeric(info[[2]][4]),as.numeric(info[[2]][6]),as.numeric(info[[2]][7]))
        ext<-c(as.numeric(info[[2]][3]),as.numeric(info[[2]][4]),as.numeric(info[[2]][6]),as.numeric(info[[2]][7]))
        
        #--> Create a a horizontally sliced las file which is reduced by the DEM
       
          command<-Fusion
          command<-paste0(command,"clipdata.exe")
          command<-paste0(command," ", "/zmin:",zrange[[j]][1])
          command<-paste0(command," ", "/zmax:",zrange[[j]][2])
          command<-paste0(command," ", "/height")
          command<-paste0(command," ", "/dtm:",gi_run,"surf_",basename(lasFiles[i]),".dtm")
          command<-paste0(command," ", "/ground")
          command<-paste0(command," ", gi_input, basename(lasFiles[i]))
          command<-paste0(command," ", gi_run,"normalised_",zrnames[j],"_",basename(lasFiles[i]))
          command<-paste0(command," ", extent)
          system(command)  
          
          
          ### NOTE Linux you need to install install winetricks mfc42
          #--> create the return density (that means counts per area)
          command<-Fusion
          command<-paste0(command, "returndensity.exe")
          command<-paste0(command," ", "/ascii")
          command<-paste0(command," ", gi_run,lasFiles[i],zrnames[j],"_density.asc "  )
          command<-paste0(command," ", res   )
          command<-paste0(command," ", gi_run,"normalised_",zrnames[j],"_",basename(lasFiles[i])   )
          system(command)  
          
          r <- raster::raster(paste0(gi_run,lasFiles[i],zrnames[j],"_density.asc"),quick=T)
          r[r[]==NAvalue(r)]<-NA  #replace arbitrary NA values with "NA"
          if (j>1) r <- raster::resample(r, rold, method = 'bilinear')
          rold<-r
          
          #--> stack the file
          density<-raster::stack(density,r,quick=T)
          #-->stack overall density
          #density<-raster::stack(density, sum(density))
          
          
        
      }
    raster::setExtent(density,ext)
    raster::crs(density)<- proj4
    od<-sum(density)
    density<-raster::stack(density, od)
    d[[i]]<-density
    density<-raster::stack()
      }
  return(d) 
   
  }
 



    


  

#'@name densityMetrics
#'@title Create height specific proportions of points and canopy height model as dtm* object from a LiDAR generated point cloud 
#'
#'@description
#' Create height specific proportions of points and canopy height model as dtm* object from a LiDAR generated point cloud 
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClassList default is \code{list(c(0,2,5,10,30))}  
#'@param res resolution for raster operations 
#'@examples
#'\dontrun{
#' # create proportions, all returns, canopy height model in dtm
#' densityMetrics(lasFiles = lasFiles, heightClassList =heights, res = 10 )
#'}
#'
#'




densityMetrics<-function(lasFiles, heightClassList, res){
  
  slices<-paste(unlist(heightClassList), collapse = ",")
  for (i in lasFiles){
    command<-Fusion
    command<-paste0(command,"densitymetrics.exe")
    command<-paste0(" /slices:", slices)
    command<-paste0(command, " ",gi_run,"surf_",i,".dtm" )
    command<-paste0(command," ", res, " ", 0.2)
    command<-paste0(command," ", gi_run,i,"densMetrics", ".dtm"   )
    command<-paste0(command," ", gi_input, i )
    system(command)
  }}






#'@name readMetrics
#'@title lists only the desired densityMetrics asc from outputfolder
#'
#'@description
#'lists only the desired densityMetrics asc from outputfolder
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClasses default is \code{list(c(0,2,5,10,30))}  
#'@examples
#'\dontrun{
#'  GridList<-readAscGridMetrics(lasFiles = lasFiles, heightClasses = heights)
#' 
#'}
#'
#'





readMetrics<-function(lasFiles, heightClassList, metrics){
  Metrics<-list()
  
  Metrics<-vector("list", length(lasFiles))
  
  for(i in 1:length(lasFiles)){
    
    maxheightClassList<-paste0(gi_output,lasFiles[i],"densMetrics","_all_returns_max_height.dtm",".asc")
    totalReturns<-paste0(gi_output,lasFiles[i],"densMetrics"," _all_returns_total_returns.dtm",".asc")
    
    Metrics[[i]][length(heightClassList[[1]])+1]<-maxheightClassList
    Metrics[[i]][length(heightClassList[[1]])+2]<-maxheightClassList
    
    
    
    for (j in 1:length(heightClassList[[1]])){
      prop<-paste0(gi_output,lasFiles[i],"densMetrics","_all_returns_slice_",j, ".dtm",".asc")
      Metrics[[i]][j]<-prop
      
      for (k in 1:length(metrics)){
        median<-paste0(gi_output, lasFiles[i], "_elevationMetrics", metrics[k],".asc" )
        Metrics[[i]][length(heightClassList[[1]])+3]<-median
      }}}
  return(Metrics)}


#'@name densityMetrics2asci
#'@title list all densityMetricsProducts and convert them into GIS-readable asc
#'
#'@description
#' list all densityMetricsProducts and convert them into GIS-readable asc
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClassList default is \code{list(c(0,2,5,10,30))}  
#'@examples
#'\dontrun{
#' 
#'densityMetrics2asci(lasFiles = lasFiles, heightClassList = heights)
#'}
#'
#'
#'
#'
densityMetrics2asci<-function(lasFiles, heightClassList){
  for (i in 1:length(lasFiles)){
    
    command<-Fusion
    command<-paste0(command, "dtm2ascii.exe")
    
    #maxHeights
    maxHeights<-paste0(gi_run,lasFiles[i],"densMetrics_","all_returns_max_height.dtm")
    command<-paste0(command, " ",maxHeights )
    command<-paste0(command, " ",gi_output, basename(maxHeights), ".asc" )
    system(command)
    
    command<-Fusion
    command<-paste0(command, "dtm2ascii.exe")
    
    #total returns
    totalReturns<-paste0(gi_run,lasFiles[i],"densMetrics_","all_returns_total_returns.dtm")
    command<-paste0(command, " ",totalReturns )
    command<-paste0(command, " ",gi_output, basename(totalReturns), ".asc" )
    system(command)
    
    #proportion in the ith layer pi
    for (j in 1:length(unlist(heightClassList))){
      prop<-paste0(gi_run,lasFiles[i],"densMetrics","_all_returns_slice_",j, ".dtm")
      command<-Fusion
      command<-paste0(command, "dtm2ascii.exe")
      command<-paste0(command, " ",prop )
      command<-paste0(command, " ",gi_output, basename(prop), ".asc" )
      system(command)
    }}}

    
    
    
    
 



  







